name: CI
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        config:
          - os: macOS-latest
            kind: test
          - os: windows-latest
            kind: test
          - os: ubuntu-latest
            kind: test
          - os: ubuntu-latest
            kind: lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.9.0
      - name: Check formatting
        if: matrix.config.kind == 'lint'
        run: |
          deno fmt --check
          deno lint --unstable
      - name: Test
        if: matrix.config.kind == 'test'
        run: |
          deno test
      - name: Test unstable
        if: matrix.config.kind == 'test'
        run: |
          deno test --coverage=cov_profile --unstable
      - name: Test coverage
        if: matrix.config.kind == 'test'
        run: |
          deno coverage --unstable cov_profile
      - name: Release info
        if: |
          matrix.config.kind == 'test' &&
          github.repository == 'udibo/mock' &&
          startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Bundle
        if: |
          env.RELEASE_VERSION != '' &&
          startsWith(matrix.config.os, 'ubuntu')
        run: |
          mkdir -p target/release
          deno bundle mod.ts target/release/mock_${RELEASE_VERSION}.js
      - name: Release
        uses: softprops/action-gh-release@v1
        if: env.RELEASE_VERSION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            target/release/mock_${{ env.RELEASE_VERSION }}.js
